# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1417, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(600, 130, 102, 13))
        self.result.setObjectName("result")
        self.check_members = QtWidgets.QCheckBox(self.centralwidget)
        self.check_members.setGeometry(QtCore.QRect(580, 170, 147, 17))
        self.check_members.setObjectName("check_members")
        self.check_leters = QtWidgets.QCheckBox(self.centralwidget)
        self.check_leters.setGeometry(QtCore.QRect(580, 200, 155, 17))
        self.check_leters.setObjectName("check_leters")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(550, 70, 205, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))
        self.check_members.setText(_translate("MainWindow", "Використовувати чифри"))
        self.check_leters.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.pushButton.setText(_translate("MainWindow", "згенерувати"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
